[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Solidity compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
gas_reports = ["*"]
gas_limit = 9223372036854775807
gas_price = 20000000000

# RPC settings for Core Chain
[rpc_endpoints]
core = "https://rpc.coredao.org"
core_testnet = "https://rpc.test.btcs.network"
mainnet = "https://eth.llamarpc.com"

# Etherscan API keys (for contract verification)
[etherscan]
core = { key = "${CORE_ETHERSCAN_API_KEY}", url = "https://scan.coredao.org/api" }
core_testnet = { key = "${CORE_TESTNET_ETHERSCAN_API_KEY}", url = "https://scan.test.btcs.network/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Formatter settings
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# Fuzz testing settings
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing settings
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# Coverage settings
[profile.coverage]
exclude = [
    "test/**/*",
    "script/**/*",
    "lib/**/*"
]

# Documentation settings
[doc]
out = "docs"
title = "CoreLiquid Protocol Documentation"
book = "book.toml"
repository = "https://github.com/coreliquid/protocol"

# Dependency remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/"
]